version: '3'
services:
  container1:
    build:
      context: ./Container1
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  container2:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./Container2:/usr/share/nginx/html:ro
