version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - container1
      - container2
    networks:
      - webnet

  container1:
    build:
      context: ./container1
    container_name: container1
    networks:
      - webnet

  container2:
    build:
      context: ./container2
    container_name: container2
    networks:
      - webnet
    ports:
      - "8000:80"

networks:
  webnet:
    driver: bridge